<!DOCTYPE html>
<html>
<head>
	<title>My ChartJS</title>
	
	<!-- Meta tags to maybe help SEO -->
        <meta name="author" content="Zubair Idris Aweda">
	
        <!-- Copied from my autogenerated linked description with some little changes -->
        <meta name="description" content="Zubair Idris' ready to use chartjs code samples.">
	
        <!-- Just my favorite languages -->
        <meta name="keywords" content="Zubair, Idris, Aweda, Zubair Idris, Zubair Idris Aweda, PHP, Chart, ChartJs, web development, data visualization">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
  	<style type="text/css">
  		canvas {width: 200px; height: 200px; margin-top: 10px;}
  		.card {margin-top: 20px;}
		a{
			color:black;
		}
		
  	</style>
</head>
<body class="container mb-5">
	<h1 style='text-align:center;'> CHARTS </h1>
	<div class="row mb-5">
		<?php include 'bar.php'; ?>
		<?php include 'line.php'; ?>
		<?php include 'pie.php'; ?>
		<?php include 'radar.php'; ?>
		<?php include 'doughnut.php'; ?>
		<?php include 'polar.php'; ?>
		<?php include 'bubble.php'; ?>
		<?php include 'scatter.php'; ?>
	</div>
	<div class="card text-center">
 	    <div class="card-body">
		    <p class="card-text"><a href="https://github.com/Zubs" target="_blank"><i class="fab fa-github"></i></a> <a href="https://twitter.com/AwedaIdris" target="_blank"><i class="fab fa-twitter"></i></a> <a href="https://web.facebook.com/AwedaIdris" target="_blank"><i class="fab fa-facebook"></i></a> <a href="https://www.instagram.com/awedazubair/" target="_blank"><i class="fab fa-instagram"></i></a> <a href="https://www.linkedin.com/in/idris-aweda-zubair-5433121a3/" target="_blank"><i class="fab fa-linkedin"></i></a></p>
  	   </div>
  	   <div class="card-footer text-muted">
    		2020 &copy; Zubair Idris Aweda
  	   </div>
	</div>
</body>
</html>
